In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.preprocessing import StandardScaler,LabelEncoder 
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score,classification_report , confusion_matrix 
import joblib
import xgboost as xgb

In [5]:
pip install xgboost

  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/5e/03/15cd49e855c62226ecf1831bbe4c8e73a4324856077a23c495538a36e557/xgboost-3.0.0-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB 245.8 kB/s eta 0:10:11
   ---------------------------------------- 0.1/150.0 MB 359.3 kB/s eta 0:06:58
   ---------------------------------------- 0.1/150.0 MB 516.7 kB/s eta 0:04:51
   ---------------------------------------- 0.2/150.0 MB 850.1 kB/s eta 0:02:57
   ---------------------------------------- 0.9/150.0 MB 2.7 MB/s eta 0:00:55
    --------------------------------------- 2.2/150.0 MB 6.2 MB/s eta 0:00:24
    --------------------------------------- 2.9/150.0 MB 7.2 MB/s eta 0:00:21
    ------------------------

In [7]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

In [10]:
df = pd.read_csv(url, sep=';')

In [11]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [12]:
df["quality"] = df["quality"].apply(lambda x : 1 if x >= 7 else 0)

In [13]:
x = df[["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]]

In [14]:
y = df["quality"]

In [16]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [17]:
x_train, x_test, y_train,y_test = train_test_split(x_scaled, y, test_size= .2, random_state=35)

In [20]:
xgb_classifier = xgb.XGBClassifier(objective="binary:logistic", eval_metric = "logloss")

In [21]:
xgb_classifier.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [22]:
xgb_classifier.predict(x_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [23]:
accuracy_score(y_test, xgb_classifier.predict(x_test) )

0.909375

In [25]:
print("classification_report \n", classification_report(y_test, xgb_classifier.predict(x_test)))

classification_report 
               precision    recall  f1-score   support

           0       0.93      0.97      0.95       268
           1       0.78      0.62      0.69        52

    accuracy                           0.91       320
   macro avg       0.85      0.79      0.82       320
weighted avg       0.90      0.91      0.90       320



In [26]:
confusion_matrix(y_test, xgb_classifier.predict(x_test))

array([[259,   9],
       [ 20,  32]], dtype=int64)

In [27]:
#hyperparameter tuning

In [31]:
param_grid = {
    "n_estimators":[50,100,200],
    "learning_rate":[0.01,.1,.2],
    "max_depth":[3,5,7,8,9,11],
    "subsample":[.7,.8,1],
    "colsample_bytree":[0.7,0.8,1]
}

In [32]:
grid_search = GridSearchCV(xgb.XGBClassifier(objective="binary:logistic", eval_metric = "logloss"),param_grid,cv=3, n_jobs=1, verbose=2)

In [33]:
grid_search.fit(x_train,y_train)

Fitting 3 folds for each of 486 candidates, totalling 1458 fits
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.7; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=50, subsample=1; total time=   0.0s
[CV] END colsample_b

GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False,
                                     eval_metric='logloss', feature_types=None,
                                     feature_weights=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraint...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=1,
             param_grid={'colsample_bytree': [0.7, 0.8, 1],
                         'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7, 8, 9, 11],
                         'n_estimators': [50, 100, 200],
                         'subsample': [0.7, 0.8, 1]},
             verbose=2)

In [34]:
grid_search.best_params_

{'colsample_bytree': 1,
 'learning_rate': 0.2,
 'max_depth': 11,
 'n_estimators': 50,
 'subsample': 0.7}

In [35]:
xgb_classifier_best_param = xgb.XGBClassifier(**grid_search.best_params_,objective="binary:logistic", eval_metric = "logloss")

In [36]:
xgb_classifier_best_param.fit (x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,
              device=None, early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=11, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=50, n_jobs=None,
              num_parallel_tree=None, ...)

In [37]:
xgb_classifier_best_param.predict(x_test)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [38]:
accuracy_score(y_test, xgb_classifier_best_param.predict(x_test))

0.90625

In [39]:
print(classification_report(y_test, xgb_classifier_best_param.predict(x_test)))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94       268
           1       0.74      0.65      0.69        52

    accuracy                           0.91       320
   macro avg       0.84      0.80      0.82       320
weighted avg       0.90      0.91      0.90       320



In [41]:
confusion_matrix(y_test, xgb_classifier_best_param.predict(x_test))

array([[256,  12],
       [ 18,  34]], dtype=int64)

In [42]:
#KNN algorithim

In [43]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

In [44]:
irish = load_iris()

In [45]:
x = irish.data
y = irish.target

In [47]:
df = pd.DataFrame(x,columns=irish.feature_names)

In [49]:
scaler = StandardScaler()

In [54]:
x_scaled = scaler.fit_transform(x)

In [55]:
x_train_knn, x_test_knn, y_train_knn, y_test_knn = train_test_split(x_scaled,y,test_size=.2,random_state=35)

In [56]:
knn = KNeighborsClassifier(n_neighbors=5)

In [58]:
knn.fit(x_train_knn,y_train_knn)

KNeighborsClassifier()

In [60]:
knn.predict(x_test_knn)

array([1, 1, 2, 1, 0, 2, 2, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 1, 1,
       2, 1, 0, 0, 0, 2, 0, 2])

In [62]:
accuracy_score(y_test_knn,knn.predict(x_test_knn))

1.0

In [ ]:
param = {"n_neighbours":np.range(1,100)}
grid_knn = GridSearchCV(KNeighborsClassifier(), param,cv=5,scoring="accuracy",n_jobs=1, verbose=1)
grid_knn.fit(x_train_knn,y_train_knn)

In [ ]:
grid_knn.best_params_